#!/usr/bin/env node
/**
 * Audio coverage audit (docs/AUDIO_DIRECTION.md). Scans every screen and
 * component for interactive elements and reports how each one sounds:
 * - <Pressable> (Focusling's sound-aware one): explicit sound, inferred, or deliberately silent (sound={null})
 * - <Button>: primary "bloop", others "tap", or an explicit override
 * - <SettingRow> switches: toggle on/off
 * - raw React Native Pressable/Touchable* (silent: must be allow-listed)
 * - <Switch>/<TextInput> used directly (typing and dev switches stay silent)
 *
 * Run: node tools/audio-audit.mjs  → writes docs/AUDIO_COVERAGE.md
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const SRC = path.join(ROOT, 'src');

/** Raw (silent) pressables that are intentional, with the reason. */
export const RAW_ALLOWED = {
  'src/ui/components/Pressable.tsx': 'the sound-aware wrapper itself',
  'src/ui/pet/AnimatedPet.tsx': 'the pet: its own species cue is played by the screen (rate-limited), not a UI tap',
};

const AREAS = [
  [/app\/onboarding/, 'Onboarding'],
  [/features\/pet|app\/\(tabs\)\/index|app\/\(child\)\/index/, 'Pet / Home'],
  [/features\/focus|app\/\(tabs\)\/focus|app\/\(child\)\/focus/, 'Focus (setup + active)'],
  [/features\/completion|session-complete/, 'Completion'],
  [/app\/wardrobe|features\/wardrobe|features\/style|app\/collection/, 'Wardrobe · Pieces · Looks · Collections · Reactions'],
  [/features\/shop|app\/\(tabs\)\/shop|app\/\(child\)\/shop/, 'Shop'],
  [/app\/inventory|features\/inventory/, 'Inventory'],
  [/missions/, 'Missions'],
  [/play|games/, 'Play'],
  [/features\/family|app\/parent|parent-gate|\(child\)/, 'Family / Child View / Parent'],
  [/settings/, 'Settings'],
  [/protection/, 'Protection'],
  [/room/, 'Room Studio'],
  [/app\/dev/, 'Developer tools'],
  [/ui\//, 'Shared UI'],
];
const areaOf = (rel) => (AREAS.find(([re]) => re.test(rel)) ?? [null, 'Other'])[1];

function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) return e.name === '__tests__' ? [] : walk(p);
    return p.endsWith('.tsx') ? [p] : [];
  });
}

/** The opening tag text starting at `i` (handles braces inside props). */
function openingTag(src, i) {
  let depth = 0;
  for (let j = i; j < src.length; j += 1) {
    const c = src[j];
    if (c === '{') depth += 1;
    else if (c === '}') depth -= 1;
    else if (c === '>' && depth === 0) return src.slice(i, j + 1);
  }
  return src.slice(i);
}

export function audit() {
  const rows = [];
  for (const file of walk(SRC)) {
    const rel = path.relative(ROOT, file);
    const src = fs.readFileSync(file, 'utf8');
    const rawImport = /import\s*\{[^}]*\b(Pressable|TouchableOpacity|TouchableHighlight|TouchableWithoutFeedback)\b[^}]*\}\s*from\s*'react-native'/.exec(src);
    const counts = { pressExplicit: 0, pressInferred: 0, pressSilent: 0, button: 0, buttonSilent: 0, settingRow: 0, rawSwitch: 0, textInput: 0 };
    const silentReasons = [];
    for (const m of src.matchAll(/<(Pressable|Button|SettingRow|Switch|TextInput)\b/g)) {
      const tag = openingTag(src, m.index);
      if (m[1] === 'Pressable') {
        if (rawImport && rawImport[1] === 'Pressable') continue;
        if (!/onPress=/.test(tag)) continue;
        if (/sound=\{null\}/.test(tag)) {
          counts.pressSilent += 1;
          const label = /accessibilityLabel=\{?[`'"]([^`'"]+)/.exec(tag)?.[1] ?? '(unlabelled)';
          silentReasons.push(label);
        } else if (/sound=/.test(tag)) counts.pressExplicit += 1;
        else counts.pressInferred += 1;
      } else if (m[1] === 'Button') {
        if (/sound=\{null\}/.test(tag)) {
          counts.buttonSilent += 1;
          silentReasons.push(/label=\{?[`'"]([^`'"]+)/.exec(tag)?.[1] ?? 'button');
        } else counts.button += 1;
      } else if (m[1] === 'SettingRow') counts.settingRow += 1;
      else if (m[1] === 'Switch' && !rel.endsWith('SettingRow.tsx')) counts.rawSwitch += 1;
      else if (m[1] === 'TextInput') counts.textInput += 1;
    }
    const total = Object.values(counts).reduce((a, b) => a + b, 0);
    if (total === 0 && !rawImport) continue;
    rows.push({ rel, area: areaOf(rel), counts, raw: rawImport ? rawImport[1] : null, allowed: RAW_ALLOWED[rel] ?? null, silentReasons });
  }
  return rows;
}

function report(rows) {
  const byArea = new Map();
  for (const r of rows) byArea.set(r.area, [...(byArea.get(r.area) ?? []), r]);
  const unexpected = rows.filter((r) => r.raw && !r.allowed);
  const lines = [
    '# Audio coverage audit',
    '',
    'Generated by `node tools/audio-audit.mjs` (re-run after UI changes). A test (`src/ui/__tests__/audioCoverage.test.ts`) fails if a raw, silent React Native pressable appears outside the allow-list.',
    '',
    `**Unexpected silent pressables: ${unexpected.length}**${unexpected.map((r) => `\n- ${r.rel} (${r.raw})`).join('')}`,
    '',
    '| Area | File | Pressable (explicit / inferred / silent) | Button (sound / silent) | Toggles | Silent by design |',
    '|---|---|---|---|---|---|',
  ];
  for (const [area, list] of [...byArea.entries()].sort()) {
    for (const r of list) {
      const c = r.counts;
      const silent = [
        ...r.silentReasons.map((s) => `“${s}”`),
        c.textInput ? `${c.textInput} text field(s)` : '',
        c.rawSwitch ? `${c.rawSwitch} dev switch(es)` : '',
        r.allowed ? `raw pressable: ${r.allowed}` : '',
      ].filter(Boolean);
      lines.push(`| ${area} | \`${r.rel.replace('src/', '')}\` | ${c.pressExplicit} / ${c.pressInferred} / ${c.pressSilent} | ${c.button} / ${c.buttonSilent} | ${c.settingRow} | ${silent.join('; ') || '—'} |`);
    }
  }
  lines.push(
    '',
    '## Intentional silences',
    '',
    '- **The pet itself** (AnimatedPet): ordinary taps play one species cue from the Home screen, at most every 0.9 s; a favourite reaction plays its own accent instead. Never during focus.',
    '- **Start Focus** button: silent, because the session\'s calm Focus Start cue plays the moment it begins.',
    '- **Buy** button: silent; the purchase cue (or the soft "unavailable" cue) plays from the result.',
    '- **Reaction previews**: silent press; the reaction\'s own accent plays with the motion.',
    '- **Room Studio Done**: the confirm cue plays explicitly before saving.',
    '- **Sliders** (room colour): silent while dragging.',
    '- **Text fields**: typing is silent.',
    '- **Disabled controls**: silent (a disabled press never fires).',
    '- **Stopping a focus session early**: no sound at all (no "failure" cue).',
    '',
  );
  return lines.join('\n');
}

if (process.argv[1] && import.meta.url.endsWith(path.basename(process.argv[1]))) {
  const rows = audit();
  fs.writeFileSync(path.join(ROOT, 'docs', 'AUDIO_COVERAGE.md'), report(rows));
  const unexpected = rows.filter((r) => r.raw && !r.allowed);
  console.log(`${rows.length} files with interactive elements; unexpected silent pressables: ${unexpected.length}`);
  if (unexpected.length) process.exitCode = 1;
}
